version: "2.3"

services:
  prometheus:
    container_name: prometheus_container
    image: prom/prometheus
    volumes:
      - ./Monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:Z
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=20d'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - '9090:9090'

  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - ./Monitoring/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"

  grafana:
    container_name: grafana_container
    image: grafana/grafana
    ports:
      - '3000:3000'