version: "2.3"

services:
  blog:
    image: vapor-service
    container_name: blog-instance
    ports:
        - "8080:8080"

  node_exporter:
    container_name: node_exporter_container
    image: prom/node-exporter
    ports:
      - '9100:9100'