global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'system'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'blog-instance-A'
    static_configs:
      - targets: ['blog-instance:8080']

