global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'service-A'
    static_configs:
      - targets: [BLOG_INSTANCE_A]

  - job_name: 'system-A'
    static_configs:
      - targets: [SYSTEM_INSTANCE_A]
